/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // ── Tokens do design system Stitch (Nexus Acadêmico) ──────────────
        'surface-tint':              '#3755c3',
        'on-surface':                '#111c2d',
        'surface-container-high':    '#dee8ff',
        'on-tertiary':               '#ffffff',
        'on-surface-variant':        '#444653',
        'inverse-surface':           '#263143',
        'on-secondary-container':    '#57657a',
        'primary':                   '#00288e',
        'primary-container':         '#1e40af',
        'surface':                   '#f9f9ff',
        'on-tertiary-container':     '#56d474',
        'surface-container-low':     '#f0f3ff',
        'on-primary':                '#ffffff',
        'on-background':             '#111c2d',
        'tertiary':                  '#003e17',
        'on-error-container':        '#93000a',
        'error':                     '#ba1a1a',
        'surface-container-lowest':  '#ffffff',
        'secondary':                 '#515f74',
        'on-secondary':              '#ffffff',
        'secondary-container':       '#d5e3fc',
        'error-container':           '#ffdad6',
        'surface-container-highest': '#d8e3fb',
        'inverse-on-surface':        '#ecf1ff',
        'on-primary-container':      '#a8b8ff',
        'secondary-fixed':           '#d5e3fc',
        'background':                '#f9f9ff',
        'surface-variant':           '#d8e3fb',
        'outline':                   '#757684',
        'surface-container':         '#e7eeff',
        'on-error':                  '#ffffff',
        'inverse-primary':           '#b8c4ff',
        'primary-fixed':             '#dde1ff',
        'surface-dim':               '#cfdaf2',
        'outline-variant':           '#c4c5d5',
        // ── Sidebar ────────────────────────────────────────────────────────
        'sidebar':                   '#0f1c2d',
        'sidebar-hover':             '#1a2d42',
        'sidebar-active':            '#1e40af',
        // ── Semânticas adicionais ──────────────────────────────────────────
        'success':                   '#16a34a',
        'success-container':         '#dcfce7',
        'warning':                   '#d97706',
        'warning-container':         '#fef3c7',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.375rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
      },
      boxShadow: {
        ambient: '0 10px 25px -5px rgba(30,41,59,0.04), 0 8px 10px -6px rgba(30,41,59,0.04)',
        modal:   '0 20px 40px -8px rgba(30,41,59,0.12)',
      },
    },
  },
  plugins: [],
}
