export { authApi, ms01, ms02, ms03, ms04, ms05 } from './httpClient'
export { authService } from './authService'
export { studentsService } from './studentsService'
export { teachersService } from './teachersService'
export { classesService } from './classesService'
export { disciplinesService } from './disciplinesService'
export { calendarService } from './calendarService'
export { assessmentsService } from './assessmentsService'
export { gradesService } from './gradesService'
export { communicationsService } from './communicationsService'
